openapi: 3.0.0
info:
  title: Agile Water API
  description: API for managing water stations and reviews.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /water_stations:
    get:
      summary: Get all water stations
      description: Retrieve all water stations with their basic information.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sn:
                      type: integer
                      example: 1
                    lat:
                      type: number
                      example: 25.033
                    lng:
                      type: number
                      example: 121.565
                    name:
                      type: string
                      example: "Station A"
                    type:
                      type: string
                      example: "飲水機"
                    access:
                      type: string
                      example: "公開"

    post:
      summary: Add a new water station
      description: Add a new water station with coordinates and detailed information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sn:
                  type: integer
                  example: 6
                name:
                  type: string
                  example: "Station C"
                addr:
                  type: string
                  example: "123 Example Street"
                type:
                  type: string
                  example: "飲水機"
                iced:
                  type: boolean
                  example: true
                cold:
                  type: boolean
                  example: true
                warm:
                  type: boolean
                  example: false
                hot:
                  type: boolean
                  example: true
                lat:
                  type: number
                  example: 25.033
                lng:
                  type: number
                  example: 121.565
                access:
                  type: string
                  example: "公開"
                phone:
                  type: string
                  example: "12345678"
                photo:
                  type: string
                  example: "https://example.com/photo.jpg"
                photo_multi:
                  type: array
                  items:
                    type: string
                  example: ["https://example.com/photo1.jpg", "https://example.com/photo2.jpg"]
                opening_hours:
                  type: string
                  example: "08:00-18:00"
                description:
                  type: string
                  example: "This is a great water station."
                offers:
                  type: string
                  example: "Free cold water"
                service:
                  type: string
                  example: "Self-service"
                score:
                  type: number
                  example: 4.5
                check_in:
                  type: integer
                  example: 10
                visit:
                  type: integer
                  example: 100
      responses:
        '201':
          description: Water station created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  sn:
                    type: integer
                    example: 6
                  name:
                    type: string
                    example: "Station C"
                  lat:
                    type: number
                    example: 25.033
                  lng:
                    type: number
                    example: 121.565
        '400':
          description: Missing required fields
        '500':
          description: Internal server error

  /water_stations/{sn}:
    get:
      summary: Get details of a specific water station
      description: Retrieve detailed information of a specific water station by its SN.
      parameters:
        - name: sn
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The SN of the water station.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  sn:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "Station A"
                  lat:
                    type: number
                    example: 25.033
                  lng:
                    type: number
                    example: 121.565
                  type:
                    type: string
                    example: "飲水機"
                  access:
                    type: string
                    example: "公開"
                  score:
                    type: number
                    example: 3.5
        '404':
          description: Water station not found

  /water_stations/nearby:
    get:
      summary: Get nearby water stations
      description: Retrieve water stations within a specified radius.
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            example: 25.033
          description: Latitude of the user's location.
        - name: lng
          in: query
          required: true
          schema:
            type: number
            example: 121.565
          description: Longitude of the user's location.
        - name: radius
          in: query
          required: true
          schema:
            type: number
            example: 1000
          description: Radius in meters to search for water stations.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sn:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Station A"
                    lat:
                      type: number
                      example: 25.033
                    lng:
                      type: number
                      example: 121.565
                    distance:
                      type: number
                      example: 200
        '400':
          description: Missing required parameters

  /water_stations/{sn}/reviews:
    get:
      summary: Get reviews for a specific water station
      description: Retrieve all reviews for a specific water station by its SN.
      parameters:
        - name: sn
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The SN of the water station.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sn:
                      type: integer
                      example: 1056
                    time:
                      type: string
                      format: date-time
                      example: "2023-08-18T12:34:56Z"
                    star:
                      type: number
                      example: 4.5
                    content:
                      type: string
                      example: "Great drinking fountain!"
                    name:
                      type: string
                      example: "John Doe"
                    img:
                      type: string
                      example: "user_image.png"
                    cmnt_img:
                      type: string
                      example: "review_image.png"

    post:
      summary: Add a review for a specific water station
      description: Submit a new review for a specific water station by its SN.
      parameters:
        - name: sn
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The SN of the water station.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                star:
                  type: number
                  example: 4.5
                content:
                  type: string
                  example: "Great drinking fountain!"
                name:
                  type: string
                  example: "John Doe"
                img:
                  type: string
                  example: "user_image.png"
                cmnt_img:
                  type: string
                  example: "review_image.png"
      responses:
        '201':
          description: Review created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  station_sn:
                    type: integer
                    example: 1
                  star:
                    type: number
                    example: 4.5
                  content:
                    type: string
                    example: "Great drinking fountain!"
        '400':
          description: Missing required fields
